apiVersion: v1
kind: Service
metadata:
  name: {{ include "executor.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "executor.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ttyd
      port: {{ .Values.service.port }}
      targetPort: ttyd
      protocol: TCP
  selector:
    {{- include "executor.selectorLabels" . | nindent 4 }}
